# Generated by Django 5.2.4 on 2025-07-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=64, unique=True)),
                ('number', models.CharField(max_length=32)),
                ('is_business', models.BooleanField(default=False)),
                ('pushname', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_type', models.CharField(blank=True, max_length=16, null=True)),
                ('is_me', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=False)),
                ('is_group', models.BooleanField(default=False)),
                ('is_wa_contact', models.BooleanField(default=False)),
                ('is_my_contact', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
