# Generated by Django 5.2.4 on 2025-07-29 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '__first__'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Título')),
                ('content', models.TextField(blank=True, default='', verbose_name='Descrição/Conteúdo')),
                ('color', models.CharField(default='#10B981', max_length=10, verbose_name='Cor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_use', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('contacts', models.ManyToManyField(blank=True, related_name='tags', to='contacts.contact', verbose_name='Contatos')),
                ('user_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.company', verbose_name='Empresa')),
            ],
        ),
    ]
