# Generated by Django 5.1.6 on 2025-07-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WahaCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=10)),
                ('request_data', models.TextField(blank=True, null=True)),
                ('response_data', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
