# Generated by Django 5.1.6 on 2025-07-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wahaplus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wahacalllog',
            name='endpoint',
            field=models.CharField(max_length=255),
        ),
    ]
